apiVersion: v1
kind: Namespace
metadata:
  name: rc-namespace
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rest-container
  namespace: rc-namespace
spec:
  replicas: 3 # Adjust the number of replicas as needed
  selector:
    matchLabels:
      app: rest-container
  template:
    metadata:
      labels:
        app: rest-container
    spec:
      containers:
      - name: rest-container
        image: zim95/rest-container:latest
        ports:
        - containerPort: 8002
---
apiVersion: v1
kind: Service
metadata:
  name: rest-container-api-service
  namespace: rc-namespace
spec:
  selector:
    app: rest-container
  ports:
  - protocol: TCP
    port: 8002
    targetPort: 8002
  type: LoadBalancer
