apiVersion: v1
kind: Namespace
metadata:
  name: rc-namespace
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: rc-namespace # Replace with the correct namespace
  name: create-list-namespaces-role
rules:
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["list", "create"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: rc-service-account
  namespace: rc-namespace
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: create-list-namespaces-binding
  namespace: rc-namespace # Replace with the correct namespace
subjects:
- kind: ServiceAccount
  name: rc-service-account
  namespace: rc-namespace
roleRef:
  kind: Role
  name: create-list-namespaces-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rest-container
  namespace: rc-namespace
spec:
  replicas: 1 # Adjust the number of replicas as needed
  selector:
    matchLabels:
      app: rest-container
  template:
    metadata:
      labels:
        app: rest-container
    spec:
      serviceAccountName: rc-service-account
      containers:
      - name: rest-container
        image: zim95/rest-container:latest
        ports:
        - containerPort: 8002
---
apiVersion: v1
kind: Service
metadata:
  name: rest-container-api-service
  namespace: rc-namespace
spec:
  selector:
    app: rest-container
  ports:
  - protocol: TCP
    port: 8002
    targetPort: 8002
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: rest-container-api-debug-service
  namespace: rc-namespace
spec:
  selector:
    app: rest-container
  ports:
  - protocol: TCP
    port: 8003
    targetPort: 8003
  type: LoadBalancer
