apiVersion: v1
kind: Namespace
metadata:
  name: rc-namespace
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  namespace: rc-namespace # Replace with the correct namespace
  name: rc-cluster-role
rules:
- apiGroups: ["", "networking.k8s.io"]
  resources: ["namespaces", "pods", "pods/exec", "networkpolicies", "services", "endpoints", "service/status", "endpoints/status", "configmaps", "secrets"]
  verbs: ["list", "create", "delete", "get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: rc-cluster-role-binding
  namespace: rc-namespace # Replace with the correct namespace
subjects:
- kind: ServiceAccount
  name: default
  namespace: rc-namespace
roleRef:
  kind: ClusterRole
  name: rc-cluster-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rest-container
  namespace: rc-namespace
spec:
  replicas: 3 # Adjust the number of replicas as needed
  selector:
    matchLabels:
      app: rest-container
  template:
    metadata:
      labels:
        app: rest-container
    spec:
      containers:
      - name: rest-container
        image: zim95/rest-container:latest
        ports:
        - containerPort: 8002
---
apiVersion: v1
kind: Service
metadata:
  name: rest-container-api-service
  namespace: rc-namespace
spec:
  selector:
    app: rest-container
  ports:
  - protocol: TCP
    port: 8002
    targetPort: 8002
  type: LoadBalancer
